### ISSUE TITLE
Dynamic content

### ISSUE THREAD

**Issue by tamiof** [futuresimple/android-floating-action-button#108]
I messed around with this library today, I really like the idea and implementation but have a few notes.
These are the issues I ran into while trying to play with this piece of code

I didn't like the fact I can't hide the FAB on scroll up/down. I read you didn't like the idea of it disappearing on scroll, but how about turning it to a more flexible code and making the people who use this library decide for themselves? As for code philosophy personally I'd prefer it this way, and I'm sure many other people who use this fantastic library would like to see this option in the future.

I would like to use dynamic content as the options popping up from the FAB. I tried adding FloatingActionButtons dynamically but had trouble with it because I couldn't add a TextView to the FloatingActionButtons and edit their appearance. I also tried setting my FloatingActionButtons in the xml but got exceptions (crashes) whenever I tried to remove the buttons from their parent - the FloatingActionsMenu. Then I tried to set the FloatingActionButtons visibility to GONE but got another exception. Only thing that was working for me for dynamic content was setting the FloatingActionButtons at the end of the hierarchy and setting their visibility to INVISIBLE.
If I'm missing something I'd love to know what I was doing wrong.

Really like what you did here. Kudos to you

**Comment by str4d** [comment]
Hiding the FAB on scroll up/down: see #1 for @chalup's reasoning behind this being `wontfix`.

Adding a TextView to the FAB: sounds like #110, either continue there or explain what you mean.

Crash when setting FAB visibility to GONE in FAM: tracked in #99.

Dynamically adding and removing FABs in FAM: IMHO the preferred way to implement this would be to toggle visibility (once #99 is closed). But there is also a `FloatingActionsMenu.addButton(FloatingActionButton)` method, so maybe it makes sense to have a `removeButton` method too. It would be more complex though, because you would also need a way to reference a particular FAB in the FAM.

**Comment by chalup** [comment]
@tamiof I didn't say I don't like the idea of hiding/showing FABs on scroll, I just don't think this functionality should be bundled in FAB code, for reasons stated in #1.

Crashes should be fixed on current master, I have also added `removeButton` method to `FloatingActionsMenu`. Let me know if you still have some issues.

**Comment by tamiof** [comment]
@chalup thanks for clarifying and the help, this actually makes more sense now.
This is one of the best libraries I encountered, it looks and feels great.

@str4d 10x for the refs

**Comment by chalup** [comment]
@tamiof I think all the issues you mentioned were addressed. Please reopen this issue if I missed anything.
