### ISSUE TITLE
Fab with RecyclerView

### ISSUE THREAD

**Issue by kiotto** [futuresimple/android-floating-action-button#174]
Is there any way to hide the fab when we scrool down a list and reappears when it is scrool up?

**Comment by chalup** [comment]
It's addressed in 'caveats' section in readme:

"Unlike some other FloatingActionButton libraries this library doesn't implement "quick return" pattern, i.e. hiding the button on scrolling down and showing it on scrolling up. That's intentional, I think that should be responsibility of another component, not the button itself."

**Comment by chalup** [comment]
Having said that, it's definitely possible to implement this behavior, I just don't think this library should be responsible for that. Just treat the FABs like any other views.

**Comment by CodeBendr** [comment]
this library solves this problem. I used it in my app. https://github.com/rutulkotak/HideOnScroll

**Comment by kiotto** [comment]
Thanks
