### ISSUE TITLE
FloatButton's label "fab_title" attribute to support RTL

### ISSUE THREAD

**Issue by alburaawi** [futuresimple/android-floating-action-button#226]
I'm not sure if RTL support is available for the FloatButton's labels. But it seems that it doesn't because when RTL is true the ```fab_title ``` doesn't change.. Is there any way I can sort this out? 
Thanks

**Comment by chalup** [comment]
Here's the screenshot of FAM with two buttons, one with title in RTL language, the other one in English:

![screen shot 2015-06-30 at 9 22 28 am](https://cloud.githubusercontent.com/assets/518902/8425793/da6df2d8-1f09-11e5-9260-1e5fa0d5e65d.png)

I had to set the labels' width to some constant value, because by default the text is centered inside the label and you can't tell the difference between LTR and RTL. What else is missing here?

**Comment by chalup** [comment]
No respone, closing. Will reopen if more info is provided.

**Comment by alburaawi** [comment]
Thank you very much and sorry about the late reply.
